theme: minima
title: Delicious food around the world
author: An excellent cook
email: jingloria36@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Make sth. delicious to eat at quarantine time! Hotpot, coconut chicken, &check out more!

# social links
twitter_username: i won't tell you
github_username:  xgloria

show_excerpts: true # set to false to remove excerpts on the homepage
